tmmikus
MGleonMG/currencycalculator pull request #12
Opened 2024-04-08 20:01 UTC by Syhnx

oaaaaaaaahhhh aua

2024-04-08 20:09 UTC, toxytoxy requested changes

2024-04-08 20:09 UTC, toxytoxy commented on src/Main/CurrencyCalculator.java
> +        String baseCurrency = "USD";
Einfach als test temporär?

2024-04-08 20:13 UTC, Syhnx commented on src/Main/CurrencyCalculator.java
> +        String baseCurrency = "USD";
ja

2024-04-08 20:13 UTC, toxytoxy requested changes

2024-04-08 20:13 UTC, toxytoxy commented on src/Main/CurrencyCalculator.java
> +        JComboBox<String> dropdown = new JComboBox<>();
Das sollten wir aber auf jeden Fall nicht in die main methode packen.. 😅

2024-04-08 20:24 UTC, toxytoxy commented on src/Main/CurrencyCalculator.java
> +        String baseCurrency = "USD";
Add mal "//TODO: remove later" pls

2024-04-09 05:39 UTC, toxytoxy approved these changes
Passt fürs erste

2024-04-09 05:40 UTC, merged