Clipboard und fixes
MGleonMG/currencycalculator pull request #23
Opened 2024-04-11 16:17 UTC by Syhnx

Musste in Calculations.java einen Datentyp erstellen, damit Clipboard richtig funktioniert. Ich hab das nochmal getestet und funktioniert wie vorhin

2024-04-11 17:00 UTC, toxytoxy requested changes
Hoffe hab nix übersehen. Würde dann später nochmal reviewen

2024-04-11 17:00 UTC, MGleonMG commented on src/GUI/GUI.java
> +    private static JButton clipBoardBtn = new JButton("Copy");
clipboardBtn*

2024-04-11 17:00 UTC, MGleonMG commented on src/GUI/GUI.java
> +    private static void addClipBoardButton() {
addCopyOutputButton*

2024-04-11 17:00 UTC, MGleonMG commented on src/GUI/GUI.java
> +        ImageIcon originalIcon = new ImageIcon(Map.class.getResource("/resources/buttons/icon_copy-button-dark.png"));
GUI.class.getResource(... *

2024-04-11 17:00 UTC, MGleonMG commented on src/GUI/GUI.java
> +        Image scaledImage = originalIcon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
hier 'n Kommentar zu wäre gut glaub ich

2024-04-11 17:00 UTC, MGleonMG commented on src/GUI/Theme.java
> +    static boolean isDarkMode = true; // TODO: Man sollte noch dran weiterarbeiten
private static bitte

2024-04-11 17:00 UTC, MGleonMG commented on src/Utils/Data/Calculations.java
> +        rechnung = Utils.adjustDecimal(amount * ExchangeRateFetcher.latestRate, 2);
Find ich nicht wirklich gut. Erstes sind hier deutsche variabeln und zweites fügt dieser change einfach nur mehr Zeilen hinzu. Fande das vorher nicht wirklich unstrukturiert. Würde sagen einfach alle changes aus der Klasse rückgängig machen.

2024-04-11 17:00 UTC, MGleonMG commented on src/Utils/Data/ExchangeRateFetcher.java
> +
??????

2024-04-11 17:00 UTC, MGleonMG commented on src/Utils/Utils.java
> +    public static void Clipboard() {
lass uns mal "copyToClipboard" nehmen. Außerdem variabeln und Funktionen immer klein Anfangen 
_(außer es sind final vars)_

2024-04-11 17:00 UTC, toxytoxy commented on src/GUI/Settings/Settings.java
> +    static boolean isDarkMode = true; // TODO: Siehe Theme Class
Kommentar weg und würde das hier auch public static machen falls möglich?

2024-04-11 18:02 UTC, Syhnx commented on src/Utils/Data/Calculations.java
> +    public static double calculation;
@toxytoxy muss drinne sein wegen Clipboard, es sei den es gibt andere Ideen

2024-04-11 19:29 UTC, toxytoxy requested changes
Ich schaus mir morgen mal auf der Arbeit an wenn ich Zeit hab so gegen Mittag.

2024-04-11 19:32 UTC, toxytoxy requested changes

2024-04-11 19:32 UTC, toxytoxy commented on src/GUI/Settings/Settings.java
> +    public  static boolean isDarkMode = true;
hier das doppelte Leerzeichen nach "public" weg wäre gut 😅

2024-04-12 06:52 UTC, toxytoxy requested changes
.

2024-04-12 07:41 UTC, Syhnx commented on src/GUI/Settings/Settings.java
> +    public  static boolean isDarkMode = true;
Hab ich so hinterlassen, damit das einheitlicher aussieht, mache es aber mal trotzdem weg

2024-04-12 07:57 UTC, toxytoxy approved these changes

2024-04-12 07:59 UTC, merged