Fix rechnung
MGleonMG/currencycalculator pull request #30
Opened 2024-04-12 22:32 UTC by Syhnx

• Alles was man eingibt wird jetzt gerechnet

TODO: Optimization Code

2024-04-13 07:22 UTC, toxytoxy requested changes

2024-04-13 07:22 UTC, toxytoxy commented on src/GUI/GUI.java
> +    public static String inputValue;
Können wir für die ganzen public statics hier einfach nen getter schreiben? Also getUserInput() und dann die vars hier auf private

2024-04-13 08:55 UTC, toxytoxy commented on src/Utils/Utils.java
> +                    + Calculations.convertCurrencies(GUI.result, GUI.result2, GUI.inputValueAsDouble);
hier dann halt auch so zeugs wie GUI.getUserInput()
Könntest hier auch mit nem enum arbeiten möglicherweise und es dann einfach so gestalten
GUI.getUserInput(Input.BASE_CUR) und "Input" ist das enum was zurück gibt welchen input du haben möchtest. Hoffe man versteht was ich mein. Probier einfach mal rum und dann mal schauen

2024-04-13 08:56 UTC, toxytoxy requested changes

2024-04-13 08:56 UTC, toxytoxy commented on src/Utils/Utils.java
>              GUI.setOuput("Ergebnis ist " + resultAsString.replace('.', ',') +
Würde hier auf jeden Fall dann den Output verbessern wenn du schon dabei bist. Irgendwas was sagt hey du hast die und die währung ausgewählt, und x euro sind y usd und rausgefunden in z millisekunden. Checkst du? 👀

2024-04-13 08:56 UTC, toxytoxy commented on src/Utils/Utils.java
> +                    + Calculations.convertCurrencies(GUI.result, GUI.result2, GUI.inputValueAsDouble);
hier dann halt auch so zeugs wie GUI.getUserInput()
Könntest hier auch mit nem enum arbeiten möglicherweise und es dann einfach so gestalten
GUI.getUserInput(Input.BASE_CUR) und "Input" ist das enum was zurück gibt welchen input du haben möchtest. Hoffe man versteht was ich mein. Probier einfach mal rum und dann mal schauen

2024-04-15 07:56 UTC, Syhnx commented
Dieser Branch wird garantiert einen Merge Conflict hinterlassen

2024-04-16 07:20 UTC, toxytoxy approved these changes

2024-04-16 07:24 UTC, toxytoxy requested changes

2024-04-16 07:24 UTC, toxytoxy commented on src/GUI/GUI.java
> +    public static double getValue() {
getAmount()*

2024-04-16 07:24 UTC, toxytoxy commented on src/Utils/Utils.java
>              GUI.setOuput("Ergebnis ist " + resultAsString.replace('.', ',') +
@Syhnx vergessen??

2024-04-17 10:12 UTC, Syhnx commented on src/Utils/Utils.java
> +                    + Calculations.convertCurrencies(GUI.result, GUI.result2, GUI.inputValueAsDouble);
• TODO erstellt

2024-04-17 10:54 UTC, toxytoxy requested changes

2024-04-17 10:54 UTC, toxytoxy commented on src/Utils/Utils.java
> +                    " Das Ergebnis ist " + Calculations.endErgebnis + " " + GUI.getTargetCur() + "\n" +
keine deutschen Variabeln bitte.

2024-04-18 06:39 UTC, toxytoxy approved these changes

2024-04-18 06:40 UTC, merged