Overhaul
MGleonMG/currencycalculator pull request #53
Opened 2024-05-07 07:05 UTC by Syhnx

2024-05-07 07:30 UTC, MGleonMG requested changes
Bitte nochmal wie gesagt Titel anpassen und 'ne description in stichpunkten pls

2024-05-07 07:31 UTC, MGleonMG commented on README.md
> +## :trollface: Autoren
lmao

2024-05-07 07:36 UTC, Syhnx commented
wollte das eigentlich erst auf draft haben

2024-05-07 07:37 UTC, Syhnx commented on README.md
> +## :trollface: Autoren
😄

2024-05-07 07:39 UTC, MGleonMG requested changes

2024-05-07 07:39 UTC, MGleonMG commented on README.md
>    <a href="#memo-license">License</a> &#xa0; | &#xa0;
kann weg

2024-05-07 07:39 UTC, MGleonMG commented on README.md
>    <a href="https://github.com/{{YOUR_GITHUB_USERNAME}}" target="_blank">Author</a>
auch weg

2024-05-07 07:39 UTC, MGleonMG commented on README.md
> +  <a href="https://currencycalculator.atlassian.net/browse/CUR-28" >Jiro</a> &#xa0; | &#xa0;
auch weg

2024-05-07 07:39 UTC, MGleonMG commented on README.md
>    <a href="#checkered_flag-starting">Starting</a> &#xa0; | &#xa0;
generell alles hier nochmal überprüfen und da drüber

2024-05-07 07:39 UTC, MGleonMG commented on README.md
> +:heavy_check_mark: Ermöglicht Theme-Wechsel zwischen Darkmode und Lightmode
wollen wir den ganzen Block hier drüber nicht auch als Stichpunkte machen wie dieses Feature 1, 2, 3 davor??

2024-05-07 07:39 UTC, MGleonMG commented on README.md
> +Before starting :checkered_flag:, you need to have [Git](https://git-scm.com), [Node](https://nodejs.org/en/) and Java Development Kit [JDK](https://www.oracle.com/java/technologies/javase-jdk15-down
Hä? NodeJS?
Und auf Englisch? Wieso?

2024-05-07 07:39 UTC, MGleonMG commented on README.md
> +Im Visual Studio Code musst du diesen Ordner erstmals öffnen. Dafür gehst du auf "File -> Open Folder" und wählst dementsprechend den neu erstellten Ordner aus. Auf dem Terminal verbindest du dich mi
mit dem*

2024-05-07 07:39 UTC, MGleonMG commented on README.md
> +TBD
?

2024-05-07 07:39 UTC, MGleonMG commented on README.md
>  [currencycalculator]
noch aktuell?

2024-05-07 07:39 UTC, MGleonMG commented on src/GUI/GUI.java
> +                            break; // Found the bracket without digits, no need to check further
deutsche Kommentare bitte

2024-05-07 07:39 UTC, MGleonMG commented on src/GUI/GUI.java
> +                            break; // Found the bracket without digits, no need to check further
hier auch

2024-05-07 07:39 UTC, MGleonMG commented on src/GUI/GUI.java
glaube die gesamte datei braucht auch noch einmal Alt + Shift + F  💀

2024-05-07 07:39 UTC, MGleonMG commented on src/lang/Language.java
> -    @SuppressWarnings("deprecation")
wieder rückgängig bitte

2024-05-07 07:57 UTC, Syhnx commented on README.md
> +Before starting :checkered_flag:, you need to have [Git](https://git-scm.com), [Node](https://nodejs.org/en/) and Java Development Kit [JDK](https://www.oracle.com/java/technologies/javase-jdk15-down
das müsste schon drin gewesen sein. JDK habe ich danach hinzugefügt

2024-05-07 07:59 UTC, Syhnx commented on README.md
> +  <a href="https://currencycalculator.atlassian.net/browse/CUR-28" >Jiro</a> &#xa0; | &#xa0;
Siehe Line 16-19, wolltest du es nicht, dass ich es hinzufüge?

2024-05-07 07:59 UTC, Syhnx commented on README.md
> +:heavy_check_mark: Ermöglicht Theme-Wechsel zwischen Darkmode und Lightmode
• 

Mit so einem Punkt?

2024-05-07 08:00 UTC, Syhnx commented on README.md
> +TBD
Da würde ich später den Download link für die Datei machen

2024-05-07 08:15 UTC, Syhnx commented
![image](https://github.com/MGleonMG/currencycalculator/assets/108582941/1503e04e-e86c-40a9-9a8d-9ecee6ed792e)

![image](https://github.com/MGleonMG/currencycalculator/assets/108582941/a4176dd0-ddb6-4002-a3c2-fe913cfe63fe)

Hab hier so einen komischen Bug

Basecur wird eigentlich (wie im 2 Bild) verwendet. Ich weiß aber nicht warum ich den Fehler erst jz bekomme

2024-05-07 08:38 UTC, MGleonMG requested changes

2024-05-07 08:38 UTC, MGleonMG commented on README.md
> +  <a href="https://currencycalculator.atlassian.net/browse/CUR-28" >Jiro</a> &#xa0; | &#xa0;
ne, ist nur der verweis auf deinen task damit man weis worums geht.

2024-05-07 08:38 UTC, MGleonMG commented on README.md
> +:heavy_check_mark: Ermöglicht Theme-Wechsel zwischen Darkmode und Lightmode
Ne
![image](https://github.com/MGleonMG/currencycalculator/assets/19241086/ad507812-3d00-4420-8782-6454ec4985f8)

2024-05-07 08:38 UTC, MGleonMG commented on README.md
> +Before starting :checkered_flag:, you need to have [Git](https://git-scm.com), [Node](https://nodejs.org/en/) and Java Development Kit [JDK](https://www.oracle.com/java/technologies/javase-jdk15-down
Ja aber du sollst das schon überprüfen und nicht einfach drin lassen xD

2024-05-07 08:38 UTC, MGleonMG commented on README.md
> +TBD
ok fair

2024-05-07 09:33 UTC, Syhnx commented
@MGleonMG @JonasOFFF 

Ich habe das Programm jetzt so gefixed, dass es nur die Buchstaben in der Klammern rausnimmt. Das Problem besteht aber noch, dass es sich mit dem ISO-Code (z.B EUR) nicht den Wechselkurs rausnehmen kann.

2024-05-07 09:40 UTC, Syhnx commented on README.md
> +:heavy_check_mark: Ermöglicht Theme-Wechsel zwischen Darkmode und Lightmode
Das ist eigentlich schon drin ":.heavy_check_mark:"

2024-05-08 07:32 UTC, MGleonMG requested changes
Dann gibst du vielleicht einfach nen falschen Wert wieder? Vllt wird der ISO Code anständig angezeigt aber diesen gibst du dann nicht richtig an die richtige Funktion wieder? Schau da einfach nochmal nach wenn du Zeit hast.

2024-05-08 08:26 UTC, Syhnx commented
Währungen die eine Jahreszahl haben, gibt es auf Google Finances nicht mehr. Daher habe ich den Code jetzt so umschrieben, dass es dem User einen Fehler gibt

2024-05-09 12:15 UTC, MGleonMG commented
scrapping this

2024-05-09 12:15 UTC, closed without merging