[WIP] add GIF
MGleonMG/currencycalculator pull request #55
Opened 2024-05-08 09:54 UTC by Syhnx

• small fixes and code commentary
• added gif

2024-05-08 09:54 UTC, Syhnx commented
Noch zeigt es keinen gif an

2024-05-10 07:19 UTC, Syhnx commented
Wir könnten vielleicht noch eine andere GIF verwenden. Das jetzige ist ein bisschen pixelig, aber das Code an sich wurde geschrieben

2024-05-10 07:27 UTC, MGleonMG requested changes

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +
leerzeile bitte weg

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +
leerzeile bitte weg

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
Wurde der Code mal formatiert mit Shift Alt F?

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +                    String[] parts = baseCurResult.split("\\)"); // 237-238 Speichert den Inhalt der Klammer, also den
Würde hier auf Zeilen irgendwie verzichten. Das kann sich ja immer ändern

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +     * Diese Methode fügt einen GIF hinzu,
ein*

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +            /*
Den Kompletten Kommentar nochmal durchlesen bitte...und dann abändern 😄

2024-05-10 07:27 UTC, MGleonMG commented on src/GUI/GUI.java
> +    private static JLabel settingsLblBtn = new JLabel(new ImageIcon("resources/buttons/settings_button.png"));
Also wir haben scheinbar das image icon hier doppelt weil es nochmal in der "drawSettingsBtn" funktion auftaucht, als neue variable? Schau mal bitte wie wir das bei anderen icons machen und dann würd ich sagen machen wir das icon setzen genau wie da. Also wenn icon setzen hier oben passiert dann auch hier oben, und wenn icon setzen immer in der Funktion gemacht wird würd ich das bei dem settings label dann auch so machen.

Aber danke dass dir das aufgefallen ist!

2024-05-10 07:57 UTC, Syhnx commented on src/GUI/GUI.java
ja

2024-05-10 09:09 UTC, Syhnx commented
Das erste GIF wirkt etwas "aggressiver" während das zweite GIF "ruhiger" ist. Entscheidet mal was besser wäre. Je nachdem kann das andere gelöscht werden

2024-05-10 09:31 UTC, MGleonMG requested changes

2024-05-10 09:31 UTC, MGleonMG commented on src/resources/buttons/GIF_Loading.gif
bitte das hier Rückgängig

2024-05-10 09:31 UTC, MGleonMG commented on src/GUI/GUI.java
> +        addGIF();
`addLoadingGIF`*

2024-05-10 10:54 UTC, MGleonMG commented
habs grad selbst gemacht..

2024-05-10 10:54 UTC, merged