GUI Layout
MGleonMG/currencycalculator pull request #64
Opened 2024-05-13 14:11 UTC by Syhnx

• Fixed Layout of GUI
• Proper Output for Errors

2024-05-13 14:14 UTC, Syhnx commented
@MGleonMG @JonasOFFF Das müsste dann durch #62 angepasst werden

2024-05-13 15:16 UTC, Syhnx commented on src/Utils/Utils.java
> +public static boolean failed;
hab das jetzt einfach als failed benannt. Sicherlich gibts da was besseres

2024-05-13 18:24 UTC, MGleonMG commented
> @MGleonMG @JonasOFFF Das müsste dann durch #62 angepasst werden

Was meinst du genau??

2024-05-13 18:34 UTC, MGleonMG requested changes
..und nochmal bitte alle files die du bearbeitet hast immer Alt Shift F

2024-05-13 18:34 UTC, MGleonMG commented on src/GUI/GUI.java
> +    private static int textWidth, textHeight;
Sieht ansich btw schonmal viel cleaner aus im GUI, good job!
Aber warum genau sind die nötig?

2024-05-13 18:34 UTC, MGleonMG commented on src/GUI/GUI.java
> +
Die Leerzeile bitte weg

2024-05-13 18:34 UTC, MGleonMG commented on src/GUI/GUI.java
> +
Die Leerzeile bitte weg

2024-05-13 18:34 UTC, MGleonMG commented on src/Utils/Data/Calculations.java
> +                Utils.failed = false;
Können wir nicht \Utils\Data\ExchangeRateFetcher\clearDataOnError() nutzen? Ist eine Funktion die ich geschrieben hab vor ner ganzen Weile. Oder hab ich da grad n Denkfehler? xD

2024-05-13 18:34 UTC, MGleonMG commented on src/Utils/Data/Calculations.java
> +                GUI.setOutput("Fehler");
nicht so 100% happy mit dem output...

2024-05-16 13:49 UTC, MGleonMG requested changes

2024-05-16 13:49 UTC, MGleonMG commented on src/Utils/Data/Calculations.java
> +                Utils.failed = false;
können wir hier vllt ne methode draus machen? Und das ganze auch nach ExchangeRateFetcher packen? Dann kannst du in ExchangeRateFetcher ne nen private static final boolean daraus machen und ne funktion namens ExchangeRateFetcher.hasFailed() die den boolean zurück gibt? Ist glaube ich cleaner

2024-05-16 14:22 UTC, MGleonMG approved these changes

2024-05-16 14:23 UTC, merged