Fix Calculation
MGleonMG/currencycalculator pull request #67
Opened 2024-05-17 15:58 UTC by Syhnx

Fixed "Permanent no Output after receiving an Error"

2024-05-17 16:04 UTC, MGleonMG approved these changes

2024-05-17 16:10 UTC, MGleonMG approved these changes

2024-05-21 07:04 UTC, MGleonMG requested changes

2024-05-21 07:04 UTC, MGleonMG commented on src/Utils/Data/ExchangeRateFetcher.java
> +        hasFailed = false;
müsste es nicht true sein? Sonst macht der Name der Funktion doch keinen Sinn?

2024-05-21 08:30 UTC, Syhnx commented on src/Utils/Data/ExchangeRateFetcher.java
> +        hasFailed = false;
Ne das ist so richtig. Wenn das auf true gesetzt wird
![image](https://github.com/MGleonMG/currencycalculator/assets/108582941/f7f00bf1-a975-41cf-8748-7cd3a2800d42)

Wird das hier gar nicht ausgeführt


![image](https://github.com/MGleonMG/currencycalculator/assets/108582941/8157d469-e022-4e5e-8782-4407b13b6950)

Etwas weiter runter setzt er das immer wieder auf false

2024-05-21 08:48 UTC, MGleonMG approved these changes

2024-05-21 08:48 UTC, merged