SettingsGUI Window rework
MGleonMG/currencycalculator pull request #74
Opened 2024-05-24 13:04 UTC by MGleonMG

- made settings window smaller
- optimized the way some components received their size and location

2024-05-27 13:44 UTC, JonasOFFF approved these changes

2024-05-31 08:26 UTC, Syhnx requested changes
@MGleonMG Ich sende gleich noch einen push raus, mit den Kommentaren dass ich geschrieben hab

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/Miscellaneous.java
> +     * TODO Implement Language
Kann gelöscht werden

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/Miscellaneous.java
> +     * Diese Methode erstellt ein Label, dass dem Benutzer zurückgibt,
Benutzer -> Nutzer

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/Miscellaneous.java
> +     * Diese Methode erstellt ein Label, dass dem Benutzer zurückgibt,
damit das alles einheitlicher ist*

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/Miscellaneous.java
> +     * Diese Methode erstellt einen Knopf, um Daten zu speichern
...um eingegebene Daten...

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/Miscellaneous.java
> +
// Setzt die gespeicherten Daten in die Variable ein

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/SettingsGUI.java
> +     * fügt dadurch die einzelnen Objekte hinzu
// Diese Methode fügt einzelne Objekte in der GUI hinzu

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/SettingsGUI.java
> +     */
// Diese Methode erstellt einen Knopf, womit man die Konfigurationen zurücksetzen kann

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/SettingsGUI.java
> +     */
"den" weg

2024-05-31 08:26 UTC, Syhnx commented on src/GUI/Components/SettingsGUI.java
> +     */
// Zeigt die Einstellungen mithilfe eines Sliders an

2024-05-31 08:26 UTC, Syhnx commented on src/Utils/RestartHelper.java
> +
// Durch diese Klasse kann das Programm sich neustarten

2024-05-31 08:26 UTC, Syhnx commented on src/lang/Language.java
> +        // } catch (NullPointerException npe) {
@MGleonMG was ist damit?

2024-05-31 08:45 UTC, Syhnx approved these changes

2024-05-31 08:46 UTC, merged